config/routes.rb
Rails.application.routes.draw do
  get '/shortest_route_lookup',
      to: 'route_planner#lookup_form',
      as: :shortest_route_lookup
  post '/shortest_route_result',
       to: 'route_planner#lookup',
       as: :shortest_route_result
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :routes, foreign_key: 'source_city_id', class_name: 'Route'
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :source_city,
             class_name: 'City',
             foreign_key: 'source_city_id'
  belongs_to :destination_city,
             class_name: 'City',
             foreign_key: 'destination_city_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/route_planner_controller.rb
class RoutePlannerController < ApplicationController
  def lookup_form
    @city_name_attributes = City.pluck(:name, :id)
  end

  def lookup
    source = City.find_by_id(params['query']['source'])
    destination = City.find_by_id(params['query']['destination'])

    success, _, distance =
      prepare_graph.shortest_path(source.id, destination.id)

    @response_text = success ? 'Connection found' : 'Connection not found'
    @distance = distance if success
  end

  private

  # TODO: Extract to helper
  def prepare_graph
    self_routes = City.pluck(:id).map { |id| [id, id, 0] }
    db_routes = Route.pluck(
      :source_city_id,
      :destination_city_id,
      :distance
    )
    Graph.new.fill_from_array(db_routes + self_routes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelerDemoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/route_planner/lookup.html.haml
=@response_text
=@distance

app/views/route_planner/lookup_form.html.haml
= form_tag(shortest_route_result_url, method: "post") do
  = select("query", "source", @city_name_attributes, {include_blank: false}, {id: 'source'})
  = select("query", "destination", @city_name_attributes, {include_blank: false}, {id: 'destination'})
  = submit_tag 'Submit', { id: 'submit_query'}